<?php

namespace LaravelMagic\Backend\Providers;

use Carbon\Laravel\ServiceProvider;

class NewBackProvider extends ServiceProvider
{

    public function boot()
    {
        if ($this->app->runningInConsole())
            $this->registerPublishing();

        $this->registerResources();
    }


    
    public function register()
    {
        $this->app->register(ResponseServiceProvider::class);
        
        parent::register(); // TODO: Change the autogenerated stub
    }

    private function registerResources()
    {
        $this->loadMigrationsFrom(__DIR__ . '/../../database/migrations');
    }

    protected function registerPublishing()
    {
        $this->publishes([
            __DIR__ . '/../../config/app.php' => config_path('app.php')
        ], 'new-back-config');
    }
}